language: python

matrix:
    include:
        - os: linux
          dist: xenial
        - os: osx

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install chardet

script:
  - python setup.py test

notifications:
  email:
    - idealities@gmail.com
