language: python

dist: xenial

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
    include:
        - os: osx

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install python; fi
  - pip install chardet

script:
  - python setup.py test

notifications:
  email:
    - idealities@gmail.com
