language: python

dist: xenial

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
    include:
        - os: osx
          language: generic
          env: PYTHON=2.7.16
        - os: osx
          language: generic
          env: PYTHON=3.7.2

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew install openssl readline
      brew outdated pyenv || brew upgrade pyenv
      pyenv install $PYTHON

      export PYENV_VERSION=$PYTHON
      export PATH="${HOME}/.pyenv/shims:${PATH}"

      python --version
    fi

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      python -m pip install -U pip
      python -m easy_install -U setuptools
    fi
  - pip install chardet

script:
  - python setup.py test

notifications:
  email:
    - idealities@gmail.com
